# Generated by Django 4.1.6 on 2023-02-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('size', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('isproduct_active', models.BooleanField()),
            ],
        ),
    ]
